---
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(rvest)
library(dplyr)
library(purrr)
```

```{r}
main_url <- "http://swcarpentry.github.io/r-novice-gapminder/"
```

```{r}
get_time <- function(href, return_value="sum"){
  child_url <- paste0(main_url, href)

  times <-
    read_html(child_url) %>%
    html_nodes("body blockquote.objectives div.col-md-3") %>%
    html_text() %>%
    strsplit("\n") %>%
    unlist() %>%
    {grep("min", ., value=TRUE)}

  if (length(times) == 0) return(0)

  times <-
    sub(".*(\\d{2}) min.*$", "\\1", times) %>%
    {suppressWarnings(as.integer(.))} %>%
    {replace(., is.na(.),0)}


  if (return_value == "teaching") {
    times[1]
  } else if (return_value == "exercise") {
    times[2]
  } else {
    sum(times)
  }
}
```

I’ll be teaching an R workshop based on the [R for Reproducible Scientific Analysis](`r main_url`) Software Carpentry lesson plan (lessons 1-10). The estimated teaching time (hrs) is:

```{r}
syllabus <-
  read_html(main_url) %>%
  html_nodes("body div.syllabus table td.col-md-3 a") %>%
  html_attr("href") %>%
  {data.frame(href = ., stringsAsFactors=FALSE)} %>%
  mutate(
    lesson_plan = ifelse(grepl("\\d{2}", href),
                         sub(".*(\\d{2}).*", "\\1", href),
                         0) %>% as.integer(),
    time_teaching = map(href, get_time, return_value="teaching") %>% unlist(),
    time_exercise = map(href, get_time, return_value="exercise") %>% unlist(),
    time_total = map(href, get_time) %>% unlist()
  )

# Time (hr) for lessons 1-10
syllabus %>%
  filter(lesson_plan <= 10) %>%
  select(starts_with("time")) %>%
  colSums() /60
```

I don't have that long, so in this repo I will condense down the lesson.

A list of R commands (parsed from the lessons) is found in [r-commands.md](r-commands.md).
